name: Update Gist

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Use Node.js version 14

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_GISTID: ${{ secrets.GH_GISTID}}
